name: movies
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  icons_launcher: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

flutter_native_splash:
  color: "#000000" 
  image: assets/images/main_logo.svg
  android_12:
    image: assets/images/main_logo.svg
    color: "#000000"
icons_launcher:
  image_path: 'assets/images/icon_lancher.jpeg'
  platforms:
    android:
      enable: true
    ios:
      enable: true